// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSBX92gXUBuLyZYXLn6EviDnZaIRRfs48',
    appId: '1:379952124956:web:50b98522c5840de0ad7bd9',
    messagingSenderId: '379952124956',
    projectId: 'flutter-chat-app-882f5',
    authDomain: 'flutter-chat-app-882f5.firebaseapp.com',
    storageBucket: 'flutter-chat-app-882f5.appspot.com',
    measurementId: 'G-WQ0FMXVXQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClsU-72wCnwiimzSwrU1Pu4se4Ry2ASPM',
    appId: '1:379952124956:android:0a75cafff7f02f57ad7bd9',
    messagingSenderId: '379952124956',
    projectId: 'flutter-chat-app-882f5',
    storageBucket: 'flutter-chat-app-882f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbtImGrIuFt6ZvRnpav7nvzUoH6dWduko',
    appId: '1:379952124956:ios:02d84adbb808b77dad7bd9',
    messagingSenderId: '379952124956',
    projectId: 'flutter-chat-app-882f5',
    storageBucket: 'flutter-chat-app-882f5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbtImGrIuFt6ZvRnpav7nvzUoH6dWduko',
    appId: '1:379952124956:ios:7834272066f58c89ad7bd9',
    messagingSenderId: '379952124956',
    projectId: 'flutter-chat-app-882f5',
    storageBucket: 'flutter-chat-app-882f5.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
